# name: flutter_todo
# description: "A new Flutter project."
# publish_to: 'none'
# version: 0.1.0

# environment:
#   sdk: '>=3.2.2 <4.0.0'

# dependencies:
#   flutter:
#     sdk: flutter
#   fluttertoast: ^8.0.8
#   flutter_slidable: ^3.0.1
#   hive: ^2.2.3
#   hive_flutter: ^1.1.0
#   google_nav_bar: ^5.0.6
#   provider: ^6.1.1

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^3.0.1
#   hive_generator: ^2.0.1
#   build_runner: ^2.4.7

# flutter:
#   uses-material-design: true
#   assets:
#   - lib/images/

name: flutter_todo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  flutter_slidable: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_nav_bar: ^5.0.6
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - lib/images/
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: lib/fonts/MaterialIcons-Regular.otf
